node main.js https://docs.okd.io/3.11/rest_api/api/v1.ConfigMap.html                                          > csv/v1.ConfigMap.csv
node main.js https://docs.okd.io/3.11/rest_api/api/v1.Endpoints.html                                          > csv/v1.Endpoints.csv
node main.js https://docs.okd.io/3.11/rest_api/api/v1.LimitRange.html                                         > csv/v1.LimitRange.csv
node main.js https://docs.okd.io/3.11/rest_api/api/v1.Namespace.html                                          > csv/v1.Namespace.csv
node main.js https://docs.okd.io/3.11/rest_api/api/v1.Node.html                                               > csv/v1.Node.csv
node main.js https://docs.okd.io/3.11/rest_api/api/v1.ResourceQuota.html                                      > csv/v1.ResourceQuota.csv
node main.js https://docs.okd.io/3.11/rest_api/api/v1.Secret.html                                             > csv/v1.Secret.csv
node main.js https://docs.okd.io/3.11/rest_api/api/v1.SecurityContextConstraints.html                         > csv/v1.SecurityContextConstraints.csv
node main.js https://docs.okd.io/3.11/rest_api/api/v1.Service.html                                            > csv/v1.Service.csv
node main.js https://docs.okd.io/3.11/rest_api/api/v1.ServiceAccount.html                                     > csv/v1.ServiceAccount.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-apps/v1beta1.Deployment.html                              > csv/v1beta1.Deployment.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-autoscaling/v1.HorizontalPodAutoscaler.html               > csv/v1.HorizontalPodAutoscaler.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-rbac.authorization.k8s.io/v1beta1.ClusterRole.html        > csv/v1beta1.ClusterRole.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-rbac.authorization.k8s.io/v1beta1.ClusterRoleBinding.html > csv/v1beta1.ClusterRoleBinding.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-rbac.authorization.k8s.io/v1beta1.Role.html               > csv/v1beta1.Role.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-rbac.authorization.k8s.io/v1beta1.RoleBinding.html        > csv/v1beta1.RoleBinding.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-authorization.openshift.io/v1.ClusterRole.html            > csv/v1.ClusterRole.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-authorization.openshift.io/v1.ClusterRoleBinding.html     > csv/v1.ClusterRoleBinding.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-authorization.openshift.io/v1.Role.html                   > csv/v1.Role.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-authorization.openshift.io/v1.RoleBinding.html            > csv/v1.RoleBinding.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-project.openshift.io/v1.Project.html                      > csv/v1.Project.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-route.openshift.io/v1.Route.html                          > csv/v1.Route.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-user.openshift.io/v1.Group.html                           > csv/v1.Group.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-user.openshift.io/v1.User.html                            > csv/v1.User.csv
node main.js https://docs.okd.io/latest/rest_api/apis-apps/v1.Deployment.html                                 > csv/v1.Deployment.csv
node main.js https://docs.okd.io/3.11/rest_api/apis-extensions/v1beta1.Ingress.html                           > csv/v1beta1.Ingress.csv